"""add_idempotency_key

Revision ID: 492a77db00f0
Revises: dc1ef2f7d581
Create Date: 2026-08-21 22:36:44.311519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492a77db00f0'
down_revision: Union[str, Sequence[str], None] = 'dc1ef2f7d581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###
