"""add_worker_id_to_jobs

Revision ID: 74f6f6b57844
Revises: 9973f08fb19c
Create Date: 2026-08-21 22:51:08.619785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f6f6b57844'
down_revision: Union[str, Sequence[str], None] = '9973f08fb19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('worker_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_worker_id'), 'jobs', ['worker_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'workers', ['worker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_worker_id'), table_name='jobs')
    op.drop_column('jobs', 'worker_id')
    # ### end Alembic commands ###
