"""add_parent_job_id

Revision ID: 9973f08fb19c
Revises: 492a77db00f0
Create Date: 2026-08-21 22:48:36.383860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9973f08fb19c'
down_revision: Union[str, Sequence[str], None] = '492a77db00f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('parent_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'jobs', ['parent_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_column('jobs', 'parent_job_id')
    # ### end Alembic commands ###
